name: Gatsby Deploy

on:
  push:
    branches: master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "maxcofie@gmail.com"
          git config --global user.name "mcofie"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
          with:
            node-version: 18.x
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci
